### ISSUE TITLE
Version bump to latest angular/rxjs versions

### ISSUE THREAD

**Issue by erdemapaydin** [angular/closure-demo#1]
I have been following this project for some time now and i wanted to say that i am very impressed by the results.
For someone who is dependent on small bundle sizes this is a very big step forward.

I have been playing around with the current state of the project and was pleasantly surprised that it also works with newer versions of angular and rxjs.

My test setup for angular version 4.1.2 and rxjs 5.4.0 was as following:
```
    "@angular/common": "^4.1.2",
    "@angular/compiler": "^4.1.2",
    "@angular/compiler-cli": "^4.1.2",
    "@angular/core": "^4.1.2",
    "@angular/platform-browser": "^4.1.2",
    "@angular/tsc-wrapped": "^4.1.2",
    "@types/jasmine": "^2.5.47",
    "clang-format": "^1.0.50",
    "concurrently": "^3.4.0",
    "google-closure-compiler": "20170409.0.0",
    "lite-server": "^2.3.0",
    "protractor": "^5.1.2",
    "rxjs": "^5.4.0",
    "source-map-explorer": "^1.3.3",
    "tsickle": "^0.21.6",
    "typescript": "^2.3.2",
    "zone.js": "^0.8.10"
```

The result was very similar in size to the current setup:
```
-- 4.1.2
  29977 May 17 09:03 dist/bundle.js.brotli
  33814 May 17 09:03 dist/bundle.js.gz
  8568 May 17 09:03 node_modules/zone.js/dist/zone.min.js.brotli
  9362 May  3 20:55 node_modules/zone.js/dist/zone.min.js.gz
```

It also works with the latest 4.2.0-beta.1-593fe5e of angular, even though the bundle size is a tiny bit bigger:
```
-- 4.2.0-beta.1-593fe5e
  30538 May 17 09:07 dist/bundle.js.brotli
  34292 May 17 09:07 dist/bundle.js.gz
  8568 May 17 09:07 node_modules/zone.js/dist/zone.min.js.brotli
  9362 May  3 20:55 node_modules/zone.js/dist/zone.min.js.gz
```

Only the latest closure compiler version still does not work as noted in https://github.com/google/closure-compiler/issues/2487

Keep up the good work!

**Comment by alexeagle** [comment]
Thanks! Do you have a few minutes to send a PR to bump the versions and update the README?

**Comment by erdemapaydin** [comment]
i created the PR
