### ISSUE TITLE
Generate externs file using `ngc`

### ISSUE THREAD

**Issue by aitboudad** [angular/closure-demo#10]
right now we can generate externs file using `tsickle` but I couldn't find a way to generate it with ngc.

@alexeagle is there an option to let `ngc` to generate `externs` ?

**Comment by alexeagle** [comment]
Sorry, it's not hooked up yet. We're working on a new tsc-wrapped that does
this (for bazel), will be in a month or two. Possibly it will only work
with bazel.

**Comment by aitboudad** [comment]
good to hear that, looking forward to it. Thanks a lot.
