### ISSUE TITLE
How to setup ngrx with closure?

### ISSUE THREAD

**Issue by vforv** [angular/closure-demo#26]
Hello,

Here is my config of closure compiler: https://github.com/vforv/angular-starter/blob/master/closure.conf

What I need to add to the config to have support for ngrx store lib?

**Comment by alexeagle** [comment]
sorry, not enough info, you didn't even say how far you got or what error you're getting.

one thing I notice in your linked file is you have `node_modules/rxjs/**.js` where I'd expect `node_modules/rxjs/**/*.js` (a recursive glob)

**Comment by vforv** [comment]
rxjs works fine...

I figure it out there is the problem with old version of ngrx...

But for the new version is easy to implement same as any angular lib....
